spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: ""
  datasource:
    url: jdbc:mysql://localhost:3306/kodilla_project?allowPublicKeyRetrieval=true&useSSL=false
    username: kodilla_user
    password: kodilla_password
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  sql:
    init:
      mode: always

weather:
  api:
    key: ae216032eff24ef68f5125541252706
    url:
      current: https://api.weatherapi.com/v1/current.json
      forecast: https://api.weatherapi.com/v1/forecast.json

frankfurter:
  api:
    url: https://api.frankfurter.dev/v1/latest
  